name: untitled
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  go_router: ^12.1.0
  flutter_form_builder: ^9.1.0
  form_builder_validators: ^11.1.2
  provider: ^6.1.2
  timeline_tile: ^2.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
